//
// Created by kbelebinda on 11/19/2019.
//

#ifndef QNX_FLIGHT_SIMULATOR_POLLINGSERVER_H
#define QNX_FLIGHT_SIMULATOR_POLLINGSERVER_H


class PollingServer {

};


#endif //QNX_FLIGHT_SIMULATOR_POLLINGSERVER_H
